version: "3.8"

services:
  # mssql:
  #     image: mcr.microsoft.com/mssql/server
  #     ports:
  #         - "1433:1433"
  #     environment:
  #         - ACCEPT_EULA=Y
  #         - SA_PASSWORD=Password!23
  #         - MSSQL_PID=Developer

  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S 192.168.0.17 -U sa -P "123" -Q "create database Financeiro_Acesso"; do sleep 5; done'

  keycloak:
    image: edsontanaka/keycloak:1.0.0
    build:
      context: ../
      dockerfile: ./src/Dockerfile
    depends_on:
      # - mssql
      - mssqlscripts
    ports:
      - "5000:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mssql
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=123
      - KC_DB_URL_HOST=192.168.0.17
      - KC_DB_URL_DATABASE=Financeiro_Acesso
      - KC_TRANSACTION_XA_ENABLED=false
      - spi-theme-static-max-age=-1 
      - spi-theme-cache-themes=false 
      - spi-theme-cache-templates=false      
    command:
      - start-dev
    networks:
      - financeiro

networks:
  financeiro:
    external: true
